// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project.Models
{
    public partial class Apply
    {
        public int Aid { get; set; }
        public int? Applicantid { get; set; }
        public int? Companyid { get; set; }
        public string Status { get; set; }
    }
}