// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project.Models
{
    public partial class Companydetails
    {
        public int Cid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}