// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project.Models
{
    public partial class Jobdetails
    {
        public int Id { get; set; }
        public int? Cid { get; set; }
        public string Compname { get; set; }
        public string Comptitle { get; set; }
        public string Compdesc { get; set; }
    }
}