// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ONLINESHOP_API.Models  
{
    public partial class ItrondbContext : DbContext
    {
        public ItrondbContext()
        {
        }

        public ItrondbContext(DbContextOptions<ItrondbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Register> Register { get; set; }
        public virtual DbSet<Userorders> Userorders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=BAN-B715VQ3;Initial Catalog=master;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Products>(entity =>
            {
                entity.HasKey(e => e.Pid)
                    .HasName("PK__products__DD37D91A434A22F5");

                entity.ToTable("products");

                entity.Property(e => e.Pid)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("pid");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Pimage)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("pimage");

                entity.Property(e => e.Pname)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("pname");

                entity.Property(e => e.Price).HasColumnName("price");
            });

            modelBuilder.Entity<Register>(entity =>
            {
                entity.HasKey(e => e.Uname)
                    .HasName("PK__Register__C7D2484FF97F26A3");

                entity.Property(e => e.Uname)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("uname");

                entity.Property(e => e.Desgination)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Dob)
                    .HasColumnType("datetime")
                    .HasColumnName("DOB");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("email");

                entity.Property(e => e.Gender).HasColumnName("gender");

                entity.Property(e => e.Password)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("password");
            });

            modelBuilder.Entity<Userorders>(entity =>
            {
                entity.HasKey(e => e.Tranid)
                    .HasName("PK__userorde__9A599E03613FA9E3");

                entity.ToTable("userorders");

                entity.Property(e => e.Tranid).HasColumnName("tranid");

                entity.Property(e => e.Pid)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("pid");

                entity.Property(e => e.Qty).HasColumnName("qty");

                entity.Property(e => e.Transdate)
                    .HasColumnType("date")
                    .HasColumnName("transdate");

                entity.Property(e => e.Username)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("username");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}