// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ONLINESHOP_API.Models
{
    public partial class Userorders
    {
        public int Tranid { get; set; }
        public string Username { get; set; }
        public string Pid { get; set; }
        public DateTime? Transdate { get; set; }
        public int? Qty { get; set; }
    }
}