// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Day7EFCore.Models
{
    public partial class Customers
    {
        public int Cuid { get; set; }
        public string Custname { get; set; }
        public int? Age { get; set; }
        public string Caddress { get; set; }
    }
}